In [12]:
test_text = """2013-10-09\t13:22\tMiami\tBoots\t99.95\tVisa
2013-10-09\t13:22\tNew York\tDVD\t9.50\tMasterCard
2013-10-09 13:22:59 I/O Error
^d8x28orz28zoijzu1z1zp1OHH3du3ixwcz114<f
1\t2\t3"""   

In [2]:
test_text

'2013-10-09\t13:22\tMiami\tBoots\t99.95\tVisa\n2013-10-09\t13:22\tNew York\tDVD\t9.50\tMasterCard\n2013-10-09 13:22:59 I/O Error\n^d8x28orz28zoijzu1z1zp1OHH3du3ixwcz114<f\n1\t2\t3'

In [38]:
# read text
from io import StringIO
readln = StringIO(test_text)
readlntxt = readln.readlines()

In [42]:
# print each line
for line in readlntxt: 
    # read each line to create a list and print
    out = line.strip().split("\t")
    print(out)

['2013-10-09', '13:22', 'Miami', 'Boots', '99.95', 'Visa']
['2013-10-09', '13:22', 'New York', 'DVD', '9.50', 'MasterCard']
['2013-10-09 13:22:59 I/O Error']
['^d8x28orz28zoijzu1z1zp1OHH3du3ixwcz114<f']
['1', '2', '3']


In [43]:
# Create Class
class solution:
    #Define function
    def solve(self, readlntxt):
        for line in readlntxt: 
            # read each line to create a list and print
            out = line.strip().split("\t")
            print(out)

In [45]:
# Create main function
if __name__ == "__main__":
    test_text = """2013-10-09\t13:22\tMiami\tBoots\t99.95\tVisa
    2013-10-09\t13:22\tNew York\tDVD\t9.50\tMasterCard
    2013-10-09 13:22:59 I/O Error
    ^d8x28orz28zoijzu1z1zp1OHH3du3ixwcz114<f
    1\t2\t3"""   
    from io import StringIO
    readln = StringIO(test_text)
    readlntxt = readln.readlines()
    
    # Declare class object
    obj = solution()
    #Call object function
    obj.solve(readlntxt)

['2013-10-09', '13:22', 'Miami', 'Boots', '99.95', 'Visa']
['2013-10-09', '13:22', 'New York', 'DVD', '9.50', 'MasterCard']
['2013-10-09 13:22:59 I/O Error']
['^d8x28orz28zoijzu1z1zp1OHH3du3ixwcz114<f']
['1', '2', '3']


In [46]:
lst = [1,2,3,4,5]

In [49]:
# List operations
lst.reverse()
lst

[5, 4, 3, 2, 1]

In [53]:
# Append
lst.append(5)
lst

[1, 2, 3, 4, 5, 5]

In [57]:
# Remove duplicate
set(lst)

{1, 2, 3, 4, 5}

In [59]:
import numpy as np
# create 2d numpy array
lst1 = [[1,2,3], [4,5,6]]
lst1
lst2 = np.array([[1,2,3], [4,5,6]])
lst2

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
# Check shape
lst2.shape

(2, 3)

In [68]:
# sum all rows
lst2.sum(axis=0)

array([5, 7, 9])

In [88]:
# ravel (flatten array)
lst3 = np.ravel(lst2)
lst3

array([1, 2, 3, 4, 5, 6])

In [93]:
# reshape (unflatten). It doesn't change the original data. only the output
np.reshape(lst3, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
#resize. Changes the original data
np.resize(lst3, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
# generate random array of 2X2
np.random.random((2,2))

array([[ 0.78168515,  0.64638538],
       [ 0.32328169,  0.95306405]])

In [17]:
# visualize using pandas
import pandas as pd
df = np.random.random((3,2))
df1 = pd.DataFrame(df)
df1

NameError: name 'np' is not defined

In [114]:
# rename pandas columns
df1.columns =['a', 'b']
df1

a         b
0  0.136897  0.476469
1  0.750820  0.504644
2  0.201677  0.113719

In [118]:
# Fetch 0,0 using index
df1.iloc[(0,0)]

0.13689663496550697

In [119]:
# Fetch 0,0 using name
df1.loc[(0,'a')]

0.13689663496550697

In [115]:
# view as dataframe using pandas
pd.DataFrame(lst2)

0  1  2
0  1  2  3
1  4  5  6

In [135]:
# convert into binary and strip unwanted values
a = bin(10)
a = str(a)
a[2:len(a)]

'1010'

In [12]:
# Input any number and find the number of continuous binary zeroes
num = input()
num = int(num)

if num < 1:
    raise TypeError("Number must be greater than 1...")

else:
    print("Number entered %s" %num)
    binum = str(bin(num))
    binum = binum[2:]
    print("binary of num %s is %s"  %(num, binum))

    #binum = '1000100'
    cval = None
    maxval = 0
    cnt = 0
    for i in range(0, len(binum)):
        cval = binum[i]        
        if binum[i] == '0': 
            #print('hit')
            cnt = cnt + 1    
            if cnt > maxval:
                maxval = cnt
        else:
            if cnt > maxval:
                maxval = cnt
            #print('miss')
            cnt = 0 

        ## This statement is to make the time complexity logN.
        ## So that we don't loop through all values
        if maxval >= len(binum)-i-1:  
            break

    print("Longest 0's sequence is %s" %maxval)

1041
Number entered 1041
binary of num 1041 is 10000010001
Longest 0's sequence is 5


In [8]:
# fibonacci series
num = input()
num = int(num)
#define numbers
a = 0
b = 1
print("printing fibonacci series")
print(a)
print(b)
for i in range(0, num-2):
    c = a+b
    print(c)
    a = b
    b = c    

5
fibonacci series
0
1
1
2
3


In [10]:
# Recursion
# sum the numbers using recursion

num = [1,3,5,7,9]

def recursion(lst):
    if len(lst) == 1:
        return(lst[0])
    else:
        return(lst[0] + recursion(lst[1:]))
    
print(recursion(num))    

25


In [16]:
# Implement a binary tree
myTree = ['a',
        ['b',
         ['d',[],[]],
         ['e',[],[]]], #close leaf
        ['c',
         ['f',[],[]],
         []
        ]]
print(myTree)
print('left subtree = ', myTree[1])
print('root = ', myTree[0])
print('right subtree = ', myTree[2])

['a', ['b', ['d', [], []], ['e', [], []]], ['c', ['f', [], []], []]]
left subtree =  ['b', ['d', [], []], ['e', [], []]]
root =  a
right subtree =  ['c', ['f', [], []], []]


In [61]:
# Rotate an array
K = 5
A = [1,2,3,4,5]
head = A[len(A)-K:]
tail = A[:len(A)-K]
head + tail

[1, 2, 3, 4, 5]

In [62]:
# Rotate an array Method 2
K = 5
A = [1,2,3,4,5]
netK = (len(A) + K) % len(A) # this will take care if K >= length(A)
print(netK)
if netK > 0:
    head = A[len(A)-netK:]
    tail = A[:-netK]
    print(head + tail)
else:
    print(A)

0
[1, 2, 3, 4, 5]


In [44]:
"""generate a list of sample data: random integers in pairs
:param L: the length of the list is double this int
:param odd: the odd integer out
"""

arr = [9, 3, 9, 3, 9, 7, 9]   
arrset = set(arr)
print("Unique elements %s" %arrset)
k = len(arrset)

# pop elements from set. remove elements from arr
# if length if even then it does not have complement
for i in range(0,k):
    arr1 = arr
    val = arrset.pop()
    print("Popping element: %s" %val)
    arr1.remove(val)
    print("Residual array: %s" %arr1)
    if val not in arr1 :
        print("Number without complement is: %s" %val)
        break


Unique elements {9, 3, 7}
Popping element: 9
Residual array: [3, 9, 3, 9, 7, 9]
Popping element: 3
Residual array: [9, 3, 9, 7, 9]
Popping element: 7
Residual array: [9, 3, 9, 9]
Number without complement is: 7


In [9]:
# fibonachi using recursion
def F(n):
    if n == 0: return 0
    elif n == 1: return 1
    else: return F(n-1)+F(n-2)

F(7)

13

In [23]:
# fibonachi using recursion and dynamic programming
def F(n, memo):
    if memo[n] is not None:
        return memo[n]
    elif n == 0: return 0
    elif n == 1: return 1
    else:
        result = F(n-1, memo) + F(n-2, memo)
        memo[n] = result
        print(memo)
        return result

# Initialize memo array
def fib_memo(n):
    memo = [None] * (n+1)
    print(memo)
    return F(n, memo)

fib_memo(8)

[None, None, None, None, None, None, None, None, None]
[None, None, 1, None, None, None, None, None, None]
[None, None, 1, 2, None, None, None, None, None]
[None, None, 1, 2, 3, None, None, None, None]
[None, None, 1, 2, 3, 5, None, None, None]
[None, None, 1, 2, 3, 5, 8, None, None]
[None, None, 1, 2, 3, 5, 8, 13, None]
[None, None, 1, 2, 3, 5, 8, 13, 21]


21

In [16]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 1.600588  , -2.51574925,  2.82355157],
       [-0.47856873,  0.16402886, -0.08965889],
       [-3.96922055,  6.18417837, -0.14769577]])